# Import Python Libraries & Read Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
ht_data = pd.read_csv("texas_affordability_census_tract.csv")
ht_data = ht_data.set_index("tract")

# Which census tract(s) has/have the highest regional cost of housing and transportation as a percentage of income?

In [12]:
max_cost = ht_data["ht_ami"].max()
print(ht_data[ht_data.ht_ami == max_cost].index)

Index(['"48029191504"', '"48201430400"', '"48479001722"'], dtype='object', name='tract')

# How many cities are in the dataset? Which cities are present in the dataset?

In [16]:
print(len(ht_data.cbsa.unique()))

69

In [15]:
print(ht_data.cbsa.unique())

['"Palestine, TX"' '"Andrews, TX"' '"Lufkin, TX"' '"Corpus Christi, TX"'
 '"Wichita Falls, TX"' '"Amarillo, TX"' '"San Antonio-New Braunfels, TX"'
 '"Houston-The Woodlands-Sugar Land, TX"' '""' '"Austin-Round Rock, TX"'
 '"Beeville, TX"' '"Killeen-Temple, TX"' '"Texarkana, TX-AR"'
 '"College Station-Bryan, TX"' '"Brownwood, TX"' '"Port Lavaca, TX"'
 '"Abilene, TX"' '"Brownsville-Harlingen, TX"' '"Jacksonville, TX"'
 '"Dallas-Fort Worth-Arlington, TX"' '"Gainesville, TX"' '"Lubbock, TX"'
 '"Lamesa, TX"' '"Hereford, TX"' '"Odessa, TX"' '"El Paso, TX"'
 '"Stephenville, TX"' '"Waco, TX"' '"Fredericksburg, TX"'
 '"Big Spring, TX"' '"Victoria, TX"' '"Pampa, TX"' '"Sherman-Denison, TX"'
 '"Longview, TX"' '"Plainview, TX"' '"Beaumont-Port Arthur, TX"'
 '"Marshall, TX"' '"Athens, TX"' '"McAllen-Edinburg-Mission, TX"'
 '"Levelland, TX"' '"Sulphur Springs, TX"' '"Borger, TX"'
 '"San Angelo, TX"' '"Alice, TX"' '"Kingsville, TX"' '"Kerrville, TX"'
 '"Paris, TX"' '"Midland, TX"' '"Bay City, TX"' '"Eagle Pass, TX"'
 '"Dumas, TX"' '"Nacogdoches, TX"' '"Corsicana, TX"' '"Sweetwater, TX"'
 '"Mineral Wells, TX"' '"Pecos, TX"' '"Snyder, TX"' '"Tyler, TX"'
 '"Rio Grande City, TX"' '"Mount Pleasant, TX"' '"Huntsville, TX"'
 '"Uvalde, TX"' '"Del Rio, TX"' '"Brenham, TX"' '"Laredo, TX"'
 '"El Campo, TX"' '"Vernon, TX"' '"Raymondville, TX"' '"Zapata, TX"']

# What is the average annual GHG emissions per household across all census tracts?

In [17]:
print(ht_data.loc[:, "co2_per_hh_local"].mean())

9.037956947914685

# Remove all rows with ANY null values

In [23]:
ht_data = ht_data.dropna(axis = 0)

# Find and filter out rows where owner occupied units + percent of renter occupied units doesn't add up to 100

In [24]:
ht_data.loc[(ht_data.pct_owner_occupied_hu + ht_data.pct_renter_occupied_hu) > 100 ]

,cbsa,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,emp_gravity,emp_ndx,block_size,intersection_density,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu
tract,,,,,,,,,,,,,,,,,,,,,
"""48201310200""","""Houston-The Woodlands-Sugar Land, TX""",1.0,1595.0,800.0,461.8,51.0,61.0,56.0,32.0,41.0,...,148694.0,96.0,3.0,383.0,457,1613.0,1906.0,1165.0,61.0,40.0

In [29]:
ht_data = ht_data.loc[(ht_data.pct_owner_occupied_hu + ht_data.pct_renter_occupied_hu) <= 100 ]

# Find rows where "ht_ami" is above 100%

In [31]:
ht_data.loc[ht_data.ht_ami > 100 ]

,cbsa,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,...,emp_gravity,emp_ndx,block_size,intersection_density,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu
tract,,,,,,,,,,,,,,,,,,,,,
"""48041002009""","""College Station-Bryan, TX""",2.0,4414.0,1515.0,4294.20,104.0,125.0,80.0,68.0,85.0,...,5118.0,87.0,52.0,31.0,2197,2340.0,2331.0,1960.0,95.0,5.0
"""48113007604""","""Dallas-Fort Worth-Arlington, TX""",3.0,3180.0,1175.0,661.25,102.0,125.0,113.0,80.0,100.0,...,68697.0,93.0,6.0,159.0,687,3980.0,4001.0,1293.0,94.0,6.0
"""48113019301""","""Dallas-Fort Worth-Arlington, TX""",3.0,3037.0,940.0,296.45,102.0,124.0,112.0,80.0,100.0,...,89151.0,94.0,8.0,142.0,804,3984.0,4001.0,927.0,96.0,4.0
"""48113019501""","""Dallas-Fort Worth-Arlington, TX""",5.0,7274.0,2174.0,712.54,101.0,123.0,111.0,79.0,98.0,...,81924.0,94.0,7.0,172.0,717,3928.0,4001.0,479.0,84.0,16.0
"""48201420900""","""Houston-The Woodlands-Sugar Land, TX""",4.0,6472.0,2184.0,865.02,101.0,123.0,111.0,79.0,98.0,...,83803.0,94.0,8.0,212.0,790,3905.0,3952.0,460.0,95.0,5.0
"""48201430600""","""Houston-The Woodlands-Sugar Land, TX""",2.0,3842.0,1221.0,926.31,104.0,126.0,113.0,80.0,100.0,...,79655.0,94.0,18.0,151.0,1101,3982.0,4001.0,2474.0,96.0,4.0
"""48215020402""","""McAllen-Edinburg-Mission, TX""",2.0,9538.0,2336.0,4708.26,103.0,124.0,67.0,64.0,80.0,...,10589.0,88.0,28.0,59.0,1179,1863.0,2110.0,1151.0,73.0,27.0
"""48427950104""","""Rio Grande City, TX""",2.0,3539.0,986.0,27751.91,102.0,122.0,51.0,49.0,61.0,...,990.0,77.0,157.0,9.0,2069,1058.0,618.0,440.0,89.0,11.0
"""48479001722""","""Laredo, TX""",2.0,6932.0,2080.0,1282.64,105.0,127.0,75.0,69.0,87.0,...,13134.0,86.0,27.0,119.0,1340,2247.0,2246.0,392.0,93.0,7.0

# Find the number of rows where the compact neighborhood score is NOT between 0 and 10

In [35]:
ht_data.loc[ht_data.compact_ndx > 10].shape[0]

0